######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 16 15:05:29 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT = core
OBJECTS_DIR = .obj
